default: &default
  adapter: mysql2
  database: finance1
  encoding: utf8mb4
  username: root
  password: Eni3d6pl#
  host: localhost
  port: 3306

development:
  <<: *default
  database: finance

test:
  <<: *default

production:
  <<: *default
  
